In [1]:
import numpy as np

In [2]:
!ls datasets/

ex1data1.txt   ex2data1.txt   ex3data1.mat
ex1data2.txt   ex2data2.txt   ex3weights.mat


In [13]:
X = np.loadtxt("datasets/ex3data1_X.txt", delimiter=",")
y = np.loadtxt("datasets/ex3data1_y.txt", delimiter=",")

In [2]:
X

NameError: name 'X' is not defined

In [1]:
X.shape

NameError: name 'X' is not defined

In [16]:
y

array([ 10.,  10.,  10., ...,   9.,   9.,   9.])

In [17]:
y.shape

(5000,)

In [ ]:
## TODO: Visualize the data.

In [25]:
theta_1 = np.loadtxt("datasets/ex3theta1.txt", delimiter=",")
theta_2 = np.loadtxt("datasets/ex3theta2.txt", delimiter=",")

In [26]:
theta_1

array([[ -2.25620000e-02,  -1.05620000e-08,   2.19410000e-09, ...,
         -1.30530000e-05,  -5.04180000e-06,   2.80460000e-09],
       [ -9.83810000e-02,   7.66170000e-09,  -9.75870000e-09, ...,
         -5.60130000e-05,   2.00940000e-07,   3.54420000e-09],
       [  1.16160000e-01,  -8.77650000e-09,   8.16040000e-09, ...,
         -1.20950000e-04,  -2.33670000e-06,  -7.50670000e-09],
       ..., 
       [ -1.83220000e-01,  -8.89270000e-09,  -9.81970000e-09, ...,
          2.35310000e-05,  -3.25480000e-06,   9.02500000e-09],
       [ -7.02100000e-01,   3.05180000e-10,   2.56060000e-09, ...,
         -8.61760000e-04,   9.43450000e-05,   3.83760000e-09],
       [ -3.50930000e-01,   8.85880000e-09,  -6.57520000e-10, ...,
         -1.80370000e-06,  -8.14460000e-06,   8.79450000e-09]])

In [27]:
theta_1.shape

(25, 401)

In [28]:
theta_2

array([[-0.761   , -1.2124  , -0.10187 , -2.3685  , -1.0578  , -2.2082  ,
         0.56384 ,  1.2111  ,  2.2103  ,  0.44456 , -1.1824  ,  1.0429  ,
        -1.6056  ,  1.3042  ,  1.3718  ,  1.7483  , -0.23366 , -1.5201  ,
         1.1532  ,  0.10368 , -0.37208 , -0.6153  , -0.12568 , -2.2719  ,
        -0.71836 , -1.2969  ],
       [-0.61785 ,  0.61559 , -1.2655  ,  1.8575  , -0.91853 , -0.055026,
        -0.3859  ,  1.2952  , -1.5684  , -0.97026 , -2.1833  , -2.8503  ,
        -2.0773  ,  1.6316  ,  0.34902 ,  1.8279  , -2.4417  , -0.8563  ,
        -0.29826 , -2.0795  , -1.2933  ,  0.89982 ,  0.28307 ,  2.3118  ,
        -2.4644  ,  1.4566  ],
       [-0.68934 , -1.9454  ,  2.0136  , -3.1232  , -0.23618 ,  1.3868  ,
         0.90982 , -1.5477  , -0.79831 , -0.656   ,  0.73538 , -2.5859  ,
         0.47211 ,  0.55349 ,  2.5126  , -2.4167  , -1.639   ,  1.2027  ,
        -1.2025  , -1.8345  , -1.8801  , -0.34056 ,  0.23692 , -1.0614  ,
         1.0276  , -0.47691 ],
       [-0.67832 , 

In [29]:
theta_2.shape

(10, 26)

In [47]:
# Insert bias unit to the data.
X_bias = np.insert(X, 0, np.ones(5000), 1)

In [54]:
X_bias.shape

(5000, 401)

In [56]:
def sigmoid(z):
    return 1 / (1 + np.e ** -z)

In [209]:
def predict(theta_1, theta_2, X):
    z_2 = np.dot(theta_1, X.T)
    a_2 = sigmoid(z_2)
    a_2_bias = np.insert(a_2, 0, np.ones(5000), 0)
    
    z_3 = np.dot(theta_2, a_2_bias)
    a_2 = sigmoid(z_3)
    h = a_2 >= 0.5
    h = h.astype(int)
    prediction = np.argmax(h, axis=0) + 1
    
    return h, prediction

In [210]:
h, prediction = predict(theta_1, theta_2, X_bias)

In [211]:
h[:, 0:10]

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [200]:
prediction[0:10]

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [201]:
y[:10]

array([ 10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.,  10.])

In [202]:
h[:, 2000:2010]

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [203]:
prediction[2000:2010]

array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4])

In [204]:
y[2000:2010]

array([ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.])

In [206]:
def get_pred_accuracy(prediction, y):
    return np.mean(prediction == y)

In [207]:
get_pred_accuracy(prediction, y)

0.94620000000000004

In [208]:
## TODO: Randomly permute examples and predict results for individual digits with visualizations.